### ISSUE TITLE
Hi Mohamed

### ISSUE THREAD

**Issue by matrix423** [MOHAMED19OS/e2script#1]
Hello Mr. Mohamed,

I like your work : simple, fast and efficient 👍 

I have a problem with this script that does not work since this week! :
_python -c "$(wget https://raw.githubusercontent.com/MOHAMED19OS/e2script/main/e2script.py -qO -)"h
--> Unable to decode the command from the command line:
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc9f' in position 5102: surrogates not allowed_

can you please fix it

thank you for your support, it's really a  good work .
best regards

**Comment by MOHAMED19OS** [comment]
Thank you for feed
I' will look for this error

**Comment by MOHAMED19OS** [comment]
@matrix423 
use this command for install
`wget -q https://raw.githubusercontent.com/MOHAMED19OS/e2script/main/e2script.py; python e2script.py && rm -rf $(pwd)/e2script.py`
